name: Exoplanets CI

on:
  push:
    branches:
      - main

jobs:
  check_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check for direct push to main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "Direct pushes to main branch are not allowed. Please create a pull request."
          exit 1

  check_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.14
      - run: npm ci
      - run: npm run lint
      - run: npm run prettier
      - run: npm test
      - run: npm run build
